project:
  type: book
  execute-dir: project
toc: true
number-sections: false
bibliography: references.bib  
highlight-style: pygments

book:
  title: "***THE ROLE OF DATA ANALYSIS IN DISTRICT LEADERSHIP***"
  subtitle: "*28 Years of Growth and Accomplishment at SCUC-ISD as Context for Today's Decisions*"
  author: "Dan Swart, Trustee, Seat 6"
  date: "today"
  reader-mode: true
  search: true
  downloads: [pdf, docx, epub]
  description: "A guiding reference for currrent and future Boards of Trustees at the Schertz-Cibolo-Universal City Independent School District"
  keyword: Schertz, Cibolo, Universal City, ISD, performance, run chart, history
  url: https://danswart.quarto.pub/scuc28yearsofdata/
  sidebar: 
    search: true
    collapse-level: 3
    pinned: true
  repo-url: https://github.com/danswart/SCUC-Book---28-Years-of-Data
  # repo-subdir: _book
  # repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: unique-1-yellow-locker.jpg
  comments:
   giscus:
     repo: danswart/SCUC-Book---28-Years-of-Data
  open-graph:
    image: https://github.com/danswart/SCUC-Book---28-Years-of-Data/unique-1-yellow-locker.jpg
    description: A compilation of 28 years of TEA data for the SCUC-ISD.
  page-footer:
    left: |
      This book was written by Dan Swart, Trustee 6, SCUC-ISD
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: unique-1-yellow-locker.jpg
  favicon: unique-1-yellow-locker.jpg
  
  chapters:
    - index.qmd
    
    - dedication.qmd
    
    - acknowledgements.qmd
    
    - how_to_use.qmd
    
    - forthestatisticallycurious.qmd
 
    - part: "District Performance"
      chapters:
        - district_perform.qmd

    - part: "Students"
      chapters:
        - student_demo.qmd
 
    - part: "Standardized Scores"
      chapters:
        - STAAR Scores by Subject.qmd
        - STAAR Scores by Student Grouping.qmd
        - sat_act.qmd
 
    - part: "Personnel"
      chapters:
        - teachers.qmd
        - staff.qmd
  
    - part: "Finances"
      chapters:
       - taxes_and_revenues.qmd
       - expenses.qmd
  
 
  
format:
  html:
    css: [swart-20240104.css, tachyons.min.css, r-colors.css]
    theme: 
      - cosmo
    grid:
      sidebar-width: 500px  # Increase this value to make the sidebar wider
      body-width: 700px     # Decrease this value to make the main content area smaller
      margin-width: 500px
    max-width: 2400px # Increase this value to make the overall page wider
    fontsize: 14pt # Adjust this value to increase or decrease the base font sizeself-contained: true
    embed-resources: false
    html-math-method: katex
    callout-appearance: simple
   
  pdf:
    documentclass: scrbook  
    include-in-header: preamble.tex
    classoption: 16pt
    includes:
      in_header: latex/preamble.tex
      before_body: latex/before_body.tex
      after_body: latex/after_body.tex
      colorlinks: true
    fontsize: 12pt
    fontfamily: palatino
    margin-left: 10mm
    margin-right: 10mm
    before_body: latex/before_body.tex
    after_body: latex/after_body.tex
    keep_tex: true
    dev: "cairo_pdf"
    latex_engine: xelatex
    citation_package: natbib
    pandoc_args: ["--top-level-division=chapter", "--lua-filter=latex/sidebar.lua"]
    quote_footer: ["\\hspace*{\\fill} ", ""]
    toc_unnumbered: true
    number_sections: false
    header-includes:
    - \usepackage{geometry}
    - \geometry{top=1.00in,left=.50in,bottom=1.00in,right=.50in}
    - \setlength\parindent{0.25in}
    - \usepackage{xcolor}
    - \usepackage{tcolorbox}
    - \usepackage{ragged2e}
    - \usepackage{hyperref}
    - \usepackage{float}
    - \hypersetup{colorlinks=true, linkcolor=MidnightBlue, urlcolor=BlueViolet, citecolor=BrickRed}
    - \urlstyle{same}
    - \graphicspath{{pbc}{img}}
    - \usepackage{caption}
    - \captionsetup[figure]{font=Large}
    - \captionsetup{font=Large}
    - \usepackage{longtable}
    - \usepackage{placeins}
linestretch: 1
fontsize: 18pt
knitr:
  opts_chunk:
    echo: false
    error: false
    warning: false
    message: false
 
