# How to Use This Book {.unnumbered}

<br>

The charts are the starting point for defining goals and improvement efforts that have practical meaning - not the jargon or euphemisms that are currently en vogue.  

Each chart tells a real story about real things.  Taken together they tell a story of how one school district met the challenges successive school boards faced.  The time frames involved provide the context needed to understand the outputs of the systems of learning in our District.

All categories and definitions are those of the Texas Education Agency and not of the author.

There are a LOT of charts contained in these chapters.  I suggest that you browse the Table of Contents and start with a chapter, or topic, you are particularly interested in and move outward from there.  To view them in order might invite a nap!

More than 152 charts visually illustrate the steady improvement of students, teachers, administration and facilities even as successive challenges arose.  The demographics of the district changed; the legislative environment changed; the district continues to become stronger.

Over the 28-year span, successive boards and superintendents navigated myriad challenges while raising most standardized scores, addressing staffing needs, and constructing new schools all while maintaining favorable student-teacher ratios, balancing administrative costs with instructional resources, and building adequate financial reserves.  All without the so-called 'good governance' rubrik so popular in today's academic circles.

Some may be interested in scholastic performance, some in financial performance, some in general demographic information, some in budgetary matters.

The Table of Contents has links to the various chapters.  Once you are in a Chapter, the sidebar on the right side has links to the various charts within the chapter.

Nearly all the plots are run charts.  With a Run Chart the exact numbers on a chart are not as important as gaining the overall range of values and any trends present in the measurements.  Is it trending up, down, or stable at a given level?  Is an upward trend good news, or bad?

Once you find a chart, or group of charts, that represent an area you feel might be important for district improvement further analysis and study can guide you to deeper insights.









